# Generated by Django 5.0.3 on 2024-05-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumers', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Fechado', 'Fechado')], default='Pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='costumers.cliente')),
            ],
        ),
    ]
