# Generated by Django 5.0.3 on 2024-05-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
