# Generated by Django 5.0.3 on 2024-05-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_ordemservico_data_conclusao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='id_cliente',
        ),
    ]
