# Generated by Django 5.0.3 on 2024-05-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='email',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='telefone',
        ),
    ]
