# Generated by Django 5.0.3 on 2024-05-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_suporte_email_remove_suporte_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suporte',
            old_name='description',
            new_name='descricao',
        ),
    ]
